name: TileAdhesive.co.uk
favicon: null
layout_spectrum: 0.6608371809124947
typography_spectrum: 0.5918184092734009
title: A New Website Soon
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#222222'
    - '#f0eee2'
    - '#746a60'
    - '#aea59c'
    - '#009265'
  brandStrength: 0.8125
  lightness: 0.9456463151145726
  saturation: 0.7315398170612752
  rhythmicContrast: 0.9518014362547547
purpose: []
