name: TileAdhesive.co.uk
favicon: null
layout_spectrum: 0.6608371809124947
typography_spectrum: 0.5918184092734009
title: A New Website Soon
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d7d9d8'
    - '#a7b2b8'
    - '#1e2132'
    - '#3d5c8b'
    - '#010113'
  brandStrength: 0.8125
  lightness: 0.9456463151145726
  saturation: 0.7315398170612752
  rhythmicContrast: 0.9518014362547547
purpose: []
